---
title: "Example R script for GloBI data"
author: "Katja Seltmann"
date: "04 15 2020"
output: html_document
---

```{r setup, include=FALSE}
# Load libraries
library(tidyverse)
library(rglobi)
library(bipartite)
library(igraph)
library(ggplot2)
library(here)
```

```{r read, warning=FALSE}
# Read in data
dat <- read_csv(here("data/Ixodes_data_unique.csv"))

# Look at data structure
#str(dat)
#View(dat)
```

```{r}
#data cleaning. Remove sourceTaxonID = no:match
dat_mod <- filter(dat, dat$sourceTaxonId != "no:match")
#View(dat_mod)
```

```{r}
#need to filter by taxon names. But first lets look at names
#unique(dat$targetTaxonGenusName)
#unique(dat$sourceTaxonGenusName)
unique(tolower(dat$targetTaxonGenusName))
unique(tolower(dat$sourceTaxonGenusName))
```

```{r}
# mutate to change to lowercase
dat_mod_filtered <- dat_mod %>%
  mutate(sourceTaxonGenusName = tolower(sourceTaxonGenusName)) %>%
  mutate(targetTaxonGenusName = tolower(targetTaxonGenusName))
unique(dat_mod_filtered$targetTaxonGenusName)
unique(dat_mod_filtered$sourceTaxonGenusName)
```

```{r}
# Filter out if the source or target are ixodes (lowercase).
dat_mod_filtered <- filter(dat_mod_filtered, sourceTaxonGenusName == "ixodes" | targetTaxonGenusName == "ixodes")
unique_interactions <- data.frame(dat_mod_filtered$targetTaxonGenusName,dat_mod_filtered$sourceTaxonGenusName)
View(unique(unique_interactions))
dim(unique(unique_interactions))
```

```{r}
# mutate taxon names to lowercase
dat_mod_filtered <- dat_mod %>%
  mutate(sourceTaxonName = tolower(sourceTaxonName)) %>%
  mutate(targetTaxonName = tolower(targetTaxonName))
```

```{r}
#get interaction dataset
all_ixodes_interactions <- data.frame(dat_mod_filtered$sourceTaxonName,dat_mod_filtered$targetTaxonName,dat_mod_filtered$interactionTypeName)
dim(unique(all_ixodes_interactions))
head(all_ixodes_interactions)
unique(dat_mod_filtered$interactionTypeName)
```
```{r}
#create a new dataframe for a network graph (vertex, edges)
bsk <- unique(data.frame(dat_mod_filtered$sourceTaxonName,dat_mod_filtered$targetTaxonName))

dim(bsk)

#describe network
bsk.network<-graph.data.frame(bsk, directed=F)

#bipartite network
g <- graph.incidence(bsk, weighted = T)

#list the vertices
V(bsk.network)

#list the edges
E(bsk.network)

#plot the graph
plot(bsk.network,vertex.size=5, vertex.label=NA)
```


